### ISSUE TITLE
URLRequest.httpBody not working

### ISSUE THREAD

**Issue by aabewhite** [skiptools/skip-foundation#7]
(As reported by user on Gitter) 

For URLRequest, this works on iOS:

```
var request = URLRequest(url: url)
request.httpMethod = requestMethod.rawValue
request.setValue(self.userAgent, forHTTPHeaderField: "User-Agent")
request.setValue("application/json", forHTTPHeaderField: "Accept")
if isLoggedIn {
    request.setValue(jwt, forHTTPHeaderField: "Authorization")
}
        
request.httpBody = httpBody
        
let (data, response) = try await URLSession.shared.data(for: request)
```

But on android the body isn't available when viewing the request using Network Inspector and when logging the error I get:

`skip.lib.ErrorException: java.io.FileNotFoundException: https://myurl`

**Comment by marcprux** [comment]
We likely just need to set the body here: https://github.com/skiptools/skip-foundation/blob/6547628a8c43bc9d628fdd04ad25f5f0bbaab328/Sources/SkipFoundation/URLSession.swift#L24-L34
